# Generated by Django 5.2.6 on 2025-09-20 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0003_dessert_drink_dessertingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDiscountRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerLoyalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifetime_pizzas', models.PositiveIntegerField(default=0)),
                ('pizzas_since_last_reward', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryZoneAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=12)),
                ('priority', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['delivery_person', 'priority', 'postal_code'],
            },
        ),
        migrations.CreateModel(
            name='OrderDiscountApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='order_item_pizza_presence',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='total_discount',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='applied_discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='pizzeria.discountcode'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='birthday_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='code_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='loyalty_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='total_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='next_available_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='dessert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='pizzeria.dessert'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='drink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='pizzeria.drink'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('base_price__gte', 0)), name='order_item_base_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price_at_order__gte', 0)), name='order_item_unit_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dessert__isnull', True), ('drink__isnull', True), ('item_type', 'pizza'), ('pizza__isnull', False)), models.Q(('dessert__isnull', True), ('drink__isnull', False), ('item_type', 'drink'), ('pizza__isnull', True)), models.Q(('dessert__isnull', False), ('drink__isnull', True), ('item_type', 'dessert'), ('pizza__isnull', True)), _connector='OR'), name='order_item_product_presence'),
        ),
        migrations.AddField(
            model_name='customerdiscountredemption',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_redemptions', to='pizzeria.customer'),
        ),
        migrations.AddField(
            model_name='customerdiscountredemption',
            name='discount_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='pizzeria.discountcode'),
        ),
        migrations.AddField(
            model_name='customerloyalty',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty', to='pizzeria.customer'),
        ),
        migrations.AddField(
            model_name='deliveryzoneassignment',
            name='delivery_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_assignments', to='pizzeria.deliveryperson'),
        ),
        migrations.AddField(
            model_name='orderdiscountapplication',
            name='discount_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_orders', to='pizzeria.discountcode'),
        ),
        migrations.AddField(
            model_name='orderdiscountapplication',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_applications', to='pizzeria.customerorder'),
        ),
        migrations.AlterUniqueTogether(
            name='customerdiscountredemption',
            unique_together={('customer', 'discount_code')},
        ),
        migrations.AlterUniqueTogether(
            name='deliveryzoneassignment',
            unique_together={('delivery_person', 'postal_code')},
        ),
    ]
